trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    exclude:
    - releases/old*
  tags:
    exclude:
    - do_not_build
  paths:
    exclude:
    - README.md
pr: none

variables:
  vmImage: 'ubuntu-latest'
  majorVersion: 1
  minorVersion: 0
  applicationName: 'todo'

# Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(majorVersion).$(minorVersion)$(Rev:.r)

stages:

- stage: BLD
  displayName: Build(CI)
  variables: {buildConfiguration: 'Release'}
  jobs:

  - job: Infrastructure
    pool:
      vmImage: $(vmImage)
    steps:
    - script: echo "Running the Infrastructure build for $(applicationName)"
      displayName: 'Starup'
    - template: 'pipelines/infrastructure/build.yml'

  - job: Application
    pool:
      vmImage: $(vmImage)
    #dependsOn: Infrastructure
    steps:
    - script: echo "Running the Application build for $(applicationName)"
      displayName: 'Starup'
    - template: 'pipelines/application/build.yml'
      parameters: {buildConfiguration: $(buildConfiguration)}

- stage: DEV
  displayName: 'DEV(CD)'
  condition: and(succeeded('BLD'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  dependsOn: 
   - BLD
  variables: 
    stage: 'dev'
  jobs:
  
  - deployment: Primary_AustraliaSouthEast
    pool:
      vmImage: $(vmImage)
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'pipelines/infrastructure/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN', location: 'australiasoutheast'}
          - template: 'pipelines/application/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN'}

- stage: QA
  displayName: 'QA(CD)'
  condition: and(succeeded('DEV'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  dependsOn: 
   - DEV
  variables: 
    stage: 'qa'
  jobs:

  - deployment: Primary_AustraliaSouthEast
    pool:
      vmImage: $(vmImage)
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'pipelines/infrastructure/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN', location: 'australiasoutheast'}
          - template: 'pipelines/application/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN'}

- stage: UAT
  displayName: 'UAT(CD)'
  condition: and(succeeded('BLD'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: 
   - BLD
  variables: 
    stage: 'uat'
  jobs:
  - deployment: Primary_AustraliaSouthEast
    pool:
      vmImage: $(vmImage)
    environment: uat
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'pipelines/infrastructure/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN', location: 'australiasoutheast'}
          - template: 'pipelines/application/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN'}

- stage: STG
  displayName: 'STAGING(CD)'
  condition: and(succeeded('UAT'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: 
   - UAT
  variables: 
    stage: 'stg'
  jobs:
  
  - deployment: Primary_AustraliaSouthEast
    pool:
      vmImage: $(vmImage)
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'pipelines/infrastructure/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN', location: 'australiasoutheast'}
          - template: 'pipelines/application/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN'}

- stage: PRD
  displayName: 'PROD(CD)'
  condition: and(succeeded('STG'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: 
   - STG
  variables: 
    stage: production
  jobs:
  
  - deployment: Primary_AustraliaSouthEast
    pool:
      vmImage: $(vmImage)
    environment: $(stage)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'pipelines/infrastructure/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN', location: 'australiasoutheast'}
          - template: 'pipelines/application/deploy.yml'
            parameters: {type: 'primary', spn: 'SPN'}
  
  - deployment: Secondary_AustraliaEast
    pool:
      vmImage: $(vmImage)
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'pipelines/infrastructure/deploy.yml'
            parameters: {type: 'secondary', spn: 'SPN', location: 'australiaeast'}
          - template: 'pipelines/application/deploy.yml'
            parameters: {type: 'secondary', spn: 'SPN'}

    
